name       : sirikali
version    : 1.4.2
release    : 3
homepage   : https://mhogomchungu.github.io/sirikali/
source     :
    - https://github.com/mhogomchungu/sirikali/archive/1.4.4.tar.gz : b5057f7d9a231454b68c17f859626eee5e05eb5c1e01a7ad7441ce5ae060ba90
license    : GPL-2.0-or-later
component  : security.crypto
summary    : SiriKali is a frontend application for managing encrypted volumes.
description: |
    SiriKali is a Qt/C++ GUI application that manages ecryptfs, cryfs, encfs, gocryptfs and securefs based encrypted folders. SiriKali can also connect to ssh servers using sshfs.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - libgcrypt-devel
setup      : |
    %cmake -DQT5=true
build      : |
    %make
install    : |
    %make_install
